[package]
name = "day1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# new-derive = "0.1.1"
# rayon = "1.5"
new-derive = { path = "../Rust/new-derive" }
num = "0.4.1"

